// Data access for the insurer console.
// Reads the live claims engine when the API is reachable; otherwise falls back to a
// static snapshot of the same synthetic batch (generated by
// backend/scripts/export_claims_demo.py) so the hosted demo always works.
import { API_BASE_URL } from '../../lib/api';

let snapshotPromise = null;
const loadSnapshot = () => {
  if (!snapshotPromise) snapshotPromise = import('../../data/claimsDemoSnapshot.json').then((m) => m.default || m);
  return snapshotPromise;
};

async function getJSON(path, timeoutMs = 8000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`${API_BASE_URL}${path}`, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function postJSON(path, body) {
  let res;
  try {
    res = await fetch(`${API_BASE_URL}${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
  } catch {
    throw new Error('엔진 API에 연결할 수 없습니다. 백엔드가 실행 중인지 확인하세요.');
  }
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(typeof data.detail === 'string' ? data.detail : `엔진 응답 오류 (HTTP ${res.status})`);
  return data;
}

export async function loadDemo() {
  try {
    const live = await getJSON('/api/claims/demo?n=300&seed=7&limit=1000');
    return { source: 'live', summary: live.summary, claims: live.claims };
  } catch {
    const snap = await loadSnapshot();
    return { source: 'snapshot', summary: snap.summary, claims: snap.claims };
  }
}

export async function loadClaimDetail(claimId) {
  try {
    return { source: 'live', ...(await getJSON(`/api/claims/demo/${encodeURIComponent(claimId)}?n=300&seed=7`)) };
  } catch {
    const snap = await loadSnapshot();
    const d = snap.details[claimId];
    return d ? { source: 'snapshot', ...d } : null;
  }
}

export async function loadEvaluation() {
  try {
    return { source: 'live', ...(await getJSON('/api/claims/evaluation?n=300&seed=7')) };
  } catch {
    const snap = await loadSnapshot();
    return { source: 'snapshot', ...snap.evaluation };
  }
}

export async function loadProcedures() {
  const snap = await loadSnapshot();
  return { procedures: snap.procedures, regionMultipliers: snap.region_multipliers };
}

// Live engine only: a new claim has no meaningful offline fallback.
export const adjudicateClaim = (claim, policy) => postJSON('/api/claims/adjudicate', { claim, policy });
export const precheckClaim = (claim) => postJSON('/api/claims/precheck', claim);

export async function extractReceipt(file) {
  const form = new FormData();
  form.append('image', file);
  let res;
  try {
    res = await fetch(`${API_BASE_URL}/api/claims/extract`, { method: 'POST', body: form });
  } catch {
    throw new Error('엔진 API에 연결할 수 없습니다.');
  }
  const body = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(body.detail || `HTTP ${res.status}`);
  return body.draft;
}
